[book]
authors = ["shadawck"]
descriptions = "Collection of tools to build beautiful command line interface in different languages."
language = "en"
multilingual = false
src = "src"
title = "Awesome CLI Framework"

[build]
build-dir = "docs"
